import bcrypt from 'bcryptjs';
import { v4 as uuidv4 } from 'uuid';
import dotenv from 'dotenv';
import { getDb, execute, queryOne, saveDb } from '../lib/db';

dotenv.config();

const PLANTS_DATA = [
  { name: 'Aloe Vera', botanicalName: 'Aloe barbadensis miller', description: 'A succulent plant species with thick fleshy leaves containing clear gel used extensively in traditional and modern medicine across Nigeria.', uses: ['Burns and wound healing','Skin moisturizer','Digestive health','Anti-inflammatory','Hair growth'], traditionalUses: ['Applied topically for skin conditions','Sap used for stomach pain','Leaf gel for sunburn relief'], family: 'Asphodelaceae', precautions: 'Internal use may cause diarrhea. Avoid during pregnancy. May interact with diabetes medications.', region: ['Southwest Nigeria','Southeast Nigeria','North Central'], imageUrl: '/plant-images/aloe-vera.jpg', yorubaName: 'Eti Erin', hausaName: 'Awoono', igboName: 'Ogolobiala', partsUsed: ['Leaves','Gel','Latex'], preparationMethods: ['Direct gel application','Juice extraction','Paste preparation'] },
  { name: 'Castor', botanicalName: 'Ricinus communis', description: 'A fast-growing plant whose seeds produce castor oil, widely used in Nigerian traditional medicine for its laxative and anti-inflammatory properties.', uses: ['Laxative','Joint pain relief','Constipation treatment','Skin conditions','Hair care'], traditionalUses: ['Leaves used as poultice for headaches','Oil used as purgative','Roots used for convulsions treatment'], family: 'Euphorbiaceae', precautions: 'Seeds are highly toxic if ingested raw. Use only processed oil. Avoid during pregnancy.', region: ['All regions of Nigeria'], imageUrl: '/plant-images/castor.jpg', yorubaName: 'Lara-pupa', hausaName: 'Zurma', igboName: 'Ogiri-isi', partsUsed: ['Seeds (processed)','Leaves','Oil'], preparationMethods: ['Cold press oil extraction','Leaf decoction','Topical oil application'] },
  { name: 'Catharanthus', botanicalName: 'Catharanthus roseus', description: 'Known as Periwinkle, this flowering plant contains alkaloids used in cancer treatment and is widely naturalized in Nigeria.', uses: ['Diabetes management','High blood pressure','Cancer treatment (vinca alkaloids)','Wound healing','Anti-microbial'], traditionalUses: ['Leaf tea for diabetes','Used for menstruation regulation','Applied to wasp stings'], family: 'Apocynaceae', precautions: 'Can lower blood sugar drastically. Potentially toxic in large doses. Consult physician.', region: ['Southwest Nigeria','Southeast Nigeria','Niger Delta'], imageUrl: '/plant-images/catharanthus.jpg', yorubaName: 'Tita-pupa', hausaName: 'Gwambaza', igboName: 'Odo-nwanyi', partsUsed: ['Leaves','Flowers','Roots'], preparationMethods: ['Leaf infusion/tea','Decoction','Poultice'] },
  { name: 'Eucalyptus', botanicalName: 'Eucalyptus globulus', description: 'A tall tree widely cultivated in Nigeria for its aromatic leaves containing eucalyptol, used primarily for respiratory conditions.', uses: ['Respiratory infections','Cough and cold relief','Decongestant','Antiseptic','Fever reducer'], traditionalUses: ['Steam inhalation for cold','Leaf decoction for malaria fever','Oil applied for body aches'], family: 'Myrtaceae', precautions: 'Essential oil is toxic if swallowed. May cause skin irritation. Keep away from children.', region: ['Plateau State','Jos area','Kaduna','North Central highlands'], imageUrl: '/plant-images/eucalyptus.jpg', yorubaName: 'Igi Eucalyptus', hausaName: 'Eucalyptus', igboName: 'Osisi Eucalyptus', partsUsed: ['Leaves','Essential oil','Bark'], preparationMethods: ['Steam inhalation','Leaf decoction','Essential oil extraction'] },
  { name: 'Ginger', botanicalName: 'Zingiber officinale', description: 'A rhizomatous herb widely cultivated and used as both spice and medicine throughout Nigeria, known for its warm pungent taste.', uses: ['Nausea and vomiting','Digestive aid','Anti-inflammatory','Pain relief','Cold and flu'], traditionalUses: ['Ginger tea for cold relief','Used in soups for digestion','Root chewed for toothache'], family: 'Zingiberaceae', precautions: 'May interact with blood thinners. Large doses may cause heartburn. Caution during pregnancy.', region: ['All regions - widely cultivated','Major production in Kaduna, Nassarawa, Gombe'], imageUrl: '/plant-images/ginger.jpg', yorubaName: 'Atale', hausaName: 'Citta', igboName: 'Jinja', partsUsed: ['Rhizome (root)','Essential oil'], preparationMethods: ['Fresh root chewing','Tea/infusion','Juice extraction','Dried powder'] },
  { name: 'Guava', botanicalName: 'Psidium guajava', description: 'A tropical fruit tree widely found across Nigeria, with leaves and fruits used extensively in traditional medicine.', uses: ['Diarrhea treatment','Diabetes management','Wound healing','Anti-microbial','Dental health'], traditionalUses: ['Leaf tea for diarrhea and dysentery','Chewing leaves for toothache','Bark decoction for skin infections'], family: 'Myrtaceae', precautions: 'May lower blood sugar. Consult physician if diabetic. Seeds may cause constipation.', region: ['All regions of Nigeria','Especially abundant in Southwest and Southeast'], imageUrl: '/plant-images/guava.jpg', yorubaName: 'Goba', hausaName: 'Gwaiba', igboName: 'Ugwoba', partsUsed: ['Leaves','Bark','Fruit','Roots'], preparationMethods: ['Leaf decoction','Fresh leaf chewing','Bark infusion'] },
  { name: 'Henna', botanicalName: 'Lawsonia inermis', description: 'A flowering plant known as Lalle in Hausa, widely used for body art and medicinal purposes, especially in Northern Nigeria.', uses: ['Skin conditions','Anti-fungal','Hair dye and care','Headache relief','Fever reduction'], traditionalUses: ['Paste applied for skin cooling','Leaf paste on forehead for fever','Used in Islamic ceremonial body decoration'], family: 'Lythraceae', precautions: 'Black henna may contain PPD causing severe reactions. Natural henna generally safe. Avoid on broken skin.', region: ['Northern Nigeria','Kano','Sokoto','Maiduguri','Northwest'], imageUrl: '/plant-images/henna.jpg', yorubaName: 'Laali', hausaName: 'Lalle', igboName: 'Uhie-oji', partsUsed: ['Leaves','Seeds','Bark'], preparationMethods: ['Dried leaf powder paste','Leaf decoction','Direct application'] },
  { name: 'Hibiscus', botanicalName: 'Hibiscus sabdariffa', description: 'Known as Zobo in Nigeria, this plant produces deep red calyces used to make a popular beverage and serves multiple medicinal purposes.', uses: ['High blood pressure','Cholesterol management','Antioxidant','Liver health','Weight management'], traditionalUses: ['Zobo drink as tonic','Calyces boiled for hypertension','Used as blood tonic'], family: 'Malvaceae', precautions: 'May lower blood pressure significantly. May interact with acetaminophen. Avoid large amounts during pregnancy.', region: ['Northern Nigeria','Kano','Katsina','Kaduna','Middle Belt'], imageUrl: '/plant-images/hibiscus.jpg', yorubaName: 'Isapa-pupa', hausaName: 'Yakuwa / Zobo', igboName: 'Ogbolo', partsUsed: ['Calyces','Leaves','Seeds'], preparationMethods: ['Calyces infusion (Zobo drink)','Dried powder','Fresh juice'] },
  { name: 'Lantana', botanicalName: 'Lantana camara', description: 'A colorful flowering shrub used in traditional medicine for various ailments including malaria, widely distributed across Nigeria.', uses: ['Malaria treatment','Wound healing','Respiratory conditions','Anti-fungal','Skin infections'], traditionalUses: ['Leaf decoction for malaria fever','Crushed leaves on wounds','Smoke from burning leaves as mosquito repellent'], family: 'Verbenaceae', precautions: 'Berries are toxic, especially to children. All parts toxic if ingested in quantity. Use with extreme caution.', region: ['All regions - widely distributed','Common in South and Middle Belt'], imageUrl: '/plant-images/lantana.jpg', yorubaName: 'Osan Elede', hausaName: 'Tabar Masar', igboName: 'Ogiriisi', partsUsed: ['Leaves','Roots (cautiously)'], preparationMethods: ['Leaf decoction','Topical poultice','Leaf smoke'] },
  { name: 'Mango', botanicalName: 'Mangifera indica', description: 'A beloved fruit tree across Nigeria with leaves, bark, and seeds used medicinally beyond its sweet edible fruit.', uses: ['Diabetes management','Diarrhea','Fever reduction','Antioxidant','Digestive health'], traditionalUses: ['Young leaf tea for diabetes','Bark decoction for diarrhea','Seed kernel for skin conditions'], family: 'Anacardiaceae', precautions: 'Mango latex can cause dermatitis in sensitive individuals. Seed kernel may interact with medications.', region: ['All regions of Nigeria','Major cultivation in Plateau, Kaduna, Cross River'], imageUrl: '/plant-images/mango.jpg', yorubaName: 'Mangoro', hausaName: 'Mangwaro', igboName: 'Mangolo', partsUsed: ['Leaves','Bark','Seed kernel','Fruit'], preparationMethods: ['Leaf tea/decoction','Bark extract','Seed kernel paste'] },
  { name: 'Mint', botanicalName: 'Mentha spicata', description: 'An aromatic herb used widely in Nigerian cooking and traditional medicine, valued for its cooling and digestive properties.', uses: ['Digestive disorders','Nausea relief','Headache','Oral health','Respiratory conditions'], traditionalUses: ['Chewing fresh leaves for bad breath','Tea for stomach upsets','Steam inhalation for blocked nose'], family: 'Lamiaceae', precautions: 'Peppermint oil can cause heartburn. Avoid pure peppermint oil for infants and young children.', region: ['Urban gardens nationwide','Southeast Nigeria','Cool highlands'], imageUrl: '/plant-images/mint.jpg', yorubaName: 'Ewe Mintisi', hausaName: "Na'na", igboName: 'Nchanwu', partsUsed: ['Leaves','Essential oil'], preparationMethods: ['Fresh leaf chewing','Tea/infusion','Essential oil steam'] },
  { name: 'Neem', botanicalName: 'Azadirachta indica', description: 'Called the village pharmacy in Nigeria, Neem is one of the most versatile medicinal trees with near-total-body utility.', uses: ['Malaria treatment and prevention','Anti-bacterial','Anti-fungal','Dental care','Skin conditions','Anti-diabetic'], traditionalUses: ['Twig used as chewing stick for dental hygiene','Leaf decoction for malaria','Bark for fever reduction'], family: 'Meliaceae', precautions: 'Internal use should be monitored. May cause liver damage in high doses. Not safe during pregnancy in large amounts.', region: ['All regions - widely planted','More abundant in North'], imageUrl: '/plant-images/neem.jpg', yorubaName: 'Dongoyaro', hausaName: 'Dogon Yaro', igboName: 'Ogelegele', partsUsed: ['Leaves','Bark','Seeds','Oil','Roots','Twigs'], preparationMethods: ['Leaf decoction','Bark tea','Seed oil extraction','Twig as chewing stick'] },
  { name: 'Onion', botanicalName: 'Allium cepa', description: 'A bulb vegetable deeply embedded in Nigerian cuisine and traditional medicine, known for its anti-microbial and cardiovascular benefits.', uses: ['Cardiovascular health','Anti-bacterial','Anti-fungal','Blood sugar regulation','Ear infections'], traditionalUses: ['Raw onion for ear pain','Onion juice for cough','Poultice for insect bites'], family: 'Amaryllidaceae', precautions: 'May thin blood - caution before surgery. Can cause acid reflux. Raw onion may irritate the stomach.', region: ['All regions - staple crop','Major production in Kebbi, Sokoto, Zamfara'], imageUrl: '/plant-images/onion.jpg', yorubaName: 'Alubosa', hausaName: 'Albasa', igboName: 'Yabasi', partsUsed: ['Bulb','Leaves','Juice'], preparationMethods: ['Raw consumption','Juice extraction','Decoction','Poultice'] },
  { name: 'Papaya', botanicalName: 'Carica papaya', description: 'A tropical fruit tree widespread across Nigeria, with leaves, seeds, and fruit all having distinct medicinal applications.', uses: ['Digestive enzyme (papain)','Anti-malarial','Wound healing','Platelet count increase','Anti-parasitic'], traditionalUses: ['Leaf tea for malaria and dengue','Seeds for intestinal parasites','Unripe fruit for digestion'], family: 'Caricaceae', precautions: 'Unripe papaya contains high latex - avoid during pregnancy. May lower blood sugar. Seeds potent - use small amounts.', region: ['All regions','Abundant in Southwest, Southeast, Niger Delta'], imageUrl: '/plant-images/papaya.jpg', yorubaName: 'Ibepe', hausaName: 'Gwanda', igboName: 'Okwuru-ojo', partsUsed: ['Leaves','Seeds','Unripe fruit','Latex'], preparationMethods: ['Leaf decoction/tea','Seed preparation','Fresh juice'] },
  { name: 'Pumpkin', botanicalName: 'Cucurbita pepo', description: 'A versatile gourd crop central to Nigerian cooking, with leaves (Ugwu) being one of the most popular and nutritious vegetables.', uses: ['Nutritional supplement','Prostate health','Anti-diabetic','Vision improvement','Immune system boost'], traditionalUses: ['Ugwu leaf soup as blood tonic','Seeds for tapeworm treatment','Leaf juice for anemia recovery'], family: 'Cucurbitaceae', precautions: 'Generally very safe. Seeds can be a choking hazard for small children. Excessive intake may affect blood clotting.', region: ['All regions','Major cultivation in Southeast, South-South, Southwest'], imageUrl: '/plant-images/pumpkin.jpg', yorubaName: 'Elegede', hausaName: 'Kabewa', igboName: 'Ugwu', partsUsed: ['Leaves','Seeds','Fruit','Roots'], preparationMethods: ['Leaf soup (Ugwu soup)','Seed extraction','Leaf juice','Decoction'] }
];

async function seed() {
  console.log('🌿 Seeding NaijaPlant AI database...');
  await getDb();

  const adminEmail = process.env.ADMIN_EMAIL || 'admin@naijaplant.ai';
  const adminPwd = process.env.ADMIN_PASSWORD || 'Admin@123';
  const hashed = await bcrypt.hash(adminPwd, 12);

  const existing = queryOne('SELECT id FROM users WHERE email = ?', [adminEmail]);
  if (!existing) {
    execute(`INSERT INTO users (id, name, email, password, role, status) VALUES (?, ?, ?, ?, 'admin', 'active')`,
      [uuidv4(), 'NaijaPlant Admin', adminEmail, hashed]);
    console.log(`✅ Admin created: ${adminEmail}`);
  } else {
    console.log(`✅ Admin exists: ${adminEmail}`);
  }

  for (const p of PLANTS_DATA) {
    const ex = queryOne('SELECT id FROM plants WHERE name = ?', [p.name]);
    if (!ex) {
      execute(`INSERT INTO plants (id,name,botanicalName,description,uses,traditionalUses,family,precautions,region,imageUrl,yorubaName,hausaName,igboName,partsUsed,preparationMethods) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`,
        [uuidv4(), p.name, p.botanicalName, p.description, JSON.stringify(p.uses), JSON.stringify(p.traditionalUses), p.family, p.precautions, JSON.stringify(p.region), p.imageUrl||null, p.yorubaName||null, p.hausaName||null, p.igboName||null, JSON.stringify(p.partsUsed), JSON.stringify(p.preparationMethods)]);
      console.log(`  🌱 ${p.name}`);
    }
  }

  saveDb();
  console.log(`\n✅ Done! Login: ${adminEmail} / ${adminPwd}`);
}

seed().catch(e => { console.error(e); process.exit(1); });
